#!/data/data/com.termux/files/usr/bin/bash
set -e

DOTFILES_DIR="/data/data/com.termux/files/usr/share/termux-dotfiles"
BACKUP_SUFFIX=".termux-dotfiles-backup"

unlink() {
    local target="$1"
    if [[ -L "$target" ]]; then
        rm -f "$target"
        # Restore backup if it exists
        if [[ -e "${target}${BACKUP_SUFFIX}" ]]; then
            mv "${target}${BACKUP_SUFFIX}" "$target"
        fi
    fi
}

unlink "$HOME/.zshrc"
unlink "$HOME/.tmux.conf"
unlink "$HOME/.termux/termux.properties"
unlink "$HOME/.config/zsh"
unlink "$HOME/.config/tmux"
unlink "$HOME/.config/termux"
unlink "$HOME/.config/nvim"